services:
  developers-dev:
    container_name: developers
    image: docker.barkfluff.com:5000/barkfluff-developers-dev:latest
    restart: always
    ports: [ "${DEVELOPERS_PORT}:${DEVELOPERS_PORT}" ]
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:${DEVELOPERS_PORT}"
      DEVELOPERS_PORT: ${DEVELOPERS_PORT}
    networks:
      - barkfluff-network

networks:
  barkfluff-network:
    driver: bridge
