services:
  fluffboard:
    image: docker.barkfluff.com/fluffboard:latest
    container_name: fluffboard
    restart: always
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Board__DatabasePath: /app/data/fluffboard.db
    networks:
      - barkfluff-network
    volumes:
      - fluffboard_data:/app/data

networks:
  barkfluff-network:
    external: true
    name: barkfluff-network

volumes:
  fluffboard_data:
