изменить этот файл для тригера сборки всех микросервисов сервера

udhfghdfsghdfsghisdfhg
dfgsdfsgsdfgdsfgjkhdfg
gsdfopdfghdfghdfghsdfg
dsfgdfslighkusdfhgkuhs
dfgloihdfisughidfshgiu
dfohgidfsgiudsgoidsfd0
