изменить этот файл для тригера сборки всех микросервисов сервера

udhfghdfsghdfsghisdfhg
dfgsdfsgsdfgdsfgjkhdfg
gsdfdfgdfgfdgddfghsdfg
dsfgdfalighkusdfhgkuhs
dfgloihdfisughidfshgiu
dfohgidfsgiudsgoidsfd0
