version: '3.8'

x-common-variables: &common-variables
  SETTINGS_SERVICE_URL: "${SETTINGS_SERVICE_URL:-http://settings:7003}"
  CONFIGURATION_SERVICE_URL: "${SETTINGS_SERVICE_URL:-http://settings:7003}"
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"

services:
  # === Основные микросервисы ===
  
  beacon:
    image: docker.barkfluff.com/barkfluff-beacon-nightly:latest
    container_name: beacon
    restart: always
    environment:
      <<: *common-variables
      BEACON_PORT: ${BEACON_PORT}
    networks:
      - barkfluff-network
    depends_on:
      - settings

  settings:
    image: docker.barkfluff.com/barkfluff-settings-nightly:latest
    container_name: settings
    restart: always
    environment:
      <<: *common-variables
      SETTINGS_HOST: "postgres"
      SETTINGS_DBPORT: "5432"
      SETTINGS_DATABASE: "${SETTINGS_DATABASE:-settings}"
      SETTINGS_ADMIN_DATABASE: "${SETTINGS_ADMIN_DATABASE:-postgres}"
      SETTINGS_USERNAME: "${POSTGRES_USER}"
      SETTINGS_PASSWORD: "${POSTGRES_PASSWORD}"
      SETTINGS_PORT: "${SETTINGS_PORT:-7003}"
      SETTINGS_SETUP_MODE: "false"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER:?set RABBITMQ_DEFAULT_USER in .env}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS:?set RABBITMQ_DEFAULT_PASS in .env}"
    networks:
      - barkfluff-network
    depends_on:
      - postgres

  files:
    image: docker.barkfluff.com/barkfluff-files-nightly:latest
    container_name: files
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  identity:
    image: docker.barkfluff.com/barkfluff-identity-nightly:latest
    container_name: identity
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  messages:
    image: docker.barkfluff.com/barkfluff-messages-nightly:latest
    container_name: messages
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  notification:
    image: docker.barkfluff.com/barkfluff-notification-nightly:latest
    container_name: notification
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  users:
    image: docker.barkfluff.com/barkfluff-users-nightly:latest
    container_name: users
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  fast-auth:
    image: docker.barkfluff.com/barkfluff-fast-auth-nightly:latest
    container_name: fast-auth
    restart: always
    environment:
      <<: *common-variables
      FASTAUTH_PORT: ${FASTAUTH_PORT}
    networks:
      - barkfluff-network
    depends_on:
      - settings

  updates:
    image: docker.barkfluff.com/barkfluff-updates-nightly:latest
    container_name: updates
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  onliner:
    image: docker.barkfluff.com/barkfluff-onliner-nightly:latest
    container_name: onliner
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  federation:
    image: docker.barkfluff.com/barkfluff-federation-nightly:latest
    container_name: federation
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  cloud-messaging:
    image: docker.barkfluff.com/barkfluff-cloud-messaging-nightly:latest
    container_name: cloud-messaging
    restart: always
    environment:
      <<: *common-variables
      Firebase__ProjectId: "${FIREBASE_PROJECT_ID}"
      Firebase__PrivateKeyId: "${FIREBASE_PRIVATE_KEY_ID}"
      Firebase__PrivateKey: "${FIREBASE_PRIVATE_KEY}"
      Firebase__ClientEmail: "${FIREBASE_CLIENT_EMAIL}"
      Firebase__ClientId: "${FIREBASE_CLIENT_ID}"
    networks:
      - barkfluff-network
    depends_on:
      - settings

  web:
    image: docker.barkfluff.com/barkfluff-web-nightly:latest
    container_name: web
    restart: always
    environment:
      <<: *common-variables
      MessagesService__Host: "http://messages:7007"
      UsersService__Host: "http://users:7001"
      FilesService__Host: "http://files:7005"
      UpdatesService__Host: "http://updates:7015"
      OnlinerService__Host: "http://onliner:7009"
      Web__Push__VapidKey: "${WEB_PUSH_VAPID_KEY}"
      Web__Push__Firebase__ApiKey: "${WEB_PUSH_FIREBASE_API_KEY}"
      Web__Push__Firebase__AuthDomain: "${WEB_PUSH_FIREBASE_AUTH_DOMAIN}"
      Web__Push__Firebase__ProjectId: "${WEB_PUSH_FIREBASE_PROJECT_ID}"
      Web__Push__Firebase__StorageBucket: "${WEB_PUSH_FIREBASE_STORAGE_BUCKET}"
      Web__Push__Firebase__MessagingSenderId: "${WEB_PUSH_FIREBASE_MESSAGING_SENDER_ID}"
      Web__Push__Firebase__AppId: "${WEB_PUSH_FIREBASE_APP_ID}"
    networks:
      - barkfluff-network
    depends_on:
      - settings
      - identity
      - users
      - messages
      - files
      - updates
      - onliner

  developers:
    image: docker.barkfluff.com/barkfluff-developers-nightly:latest
    container_name: developers
    restart: always
    environment:
      <<: *common-variables
      DEVELOPERS_PORT: ${DEVELOPERS_PORT:-7020}
      DEVELOPERS_HTTP1PORT: ${DEVELOPERS_HTTP1PORT:-7021}
    networks:
      - barkfluff-network
    depends_on:
      - settings

  calls:
    image: docker.barkfluff.com/barkfluff-calls-nightly:latest
    container_name: calls
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings

  bots:
    image: docker.barkfluff.com/barkfluff-bots-nightly:latest
    container_name: bots
    restart: always
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - settings
      - users
      - messages
      - files

  # === Панель администрирования ===

  admin-panel:
    image: docker.barkfluff.com/barkfluff-admin-panel-nightly:latest
    container_name: admin-panel
    restart: always
    user: root
    environment:
      <<: *common-variables
      SettingsService__Host: "${SETTINGS_SERVICE_URL:-http://settings:7003}"
      Telegram__BotToken: "${TELEGRAM_BOT_TOKEN}"
      Telegram__Admins: "${TELEGRAM_ADMINS}"
      Telegram__Proxy__Url: "${TELEGRAM_PROXY_URL:-}"
      Telegram__Proxy__Username: "${TELEGRAM_PROXY_USERNAME:-}"
      Telegram__Proxy__Password: "${TELEGRAM_PROXY_PASSWORD:-}"
      Seq__ServerUrl: "http://seq:80"
      Seq__ApiKey: "${SEQ_API_KEY:-}"
      UsersService__Host: "${USERS_SERVICE_HOST}"
      FilesService__Host: "${FILES_SERVICE_HOST}"
      UsersService__Token: "${USERS_SERVICE_TOKEN}"
      FilesService__Token: "${FILES_SERVICE_TOKEN}"
      MessagesService__Host: "${MESSAGES_SERVICE_HOST:-http://messages:7007}"
      MessagesService__Token: "${MESSAGES_SERVICE_TOKEN:-}"
      IdentityService__Host: "${IDENTITY_SERVICE_HOST}"
      IdentityService__Token: "${IDENTITY_SERVICE_TOKEN}"
      BotsService__Host: "${BOTS_SERVICE_HOST:-http://bots:7027}"
      BotsService__Token: "${BOTS_SERVICE_TOKEN:-}"
      Mail__SmtpHost: "${MAIL_SMTP_HOST:-}"
      Mail__SmtpPort: "${MAIL_SMTP_PORT:-587}"
      Mail__ImapHost: "${MAIL_IMAP_HOST:-}"
      Mail__ImapPort: "${MAIL_IMAP_PORT:-993}"
      Mail__ImapSecurity: "${MAIL_IMAP_SECURITY:-SslOnConnect}"
      Mail__SmtpSecurity: "${MAIL_SMTP_SECURITY:-Auto}"
      Mail__AcceptInvalidCertificates: "${MAIL_ACCEPT_INVALID_CERTIFICATES:-false}"
      Mail__Accounts__0__Address: "support@barkfluff.com"
      Mail__Accounts__0__Password: "${MAIL_SUPPORT_PASSWORD:-}"
      Mail__Accounts__1__Address: "help@barkfluff.com"
      Mail__Accounts__1__Password: "${MAIL_HELP_PASSWORD:-}"
      Mail__Accounts__2__Address: "noreply@barkfluff.com"
      Mail__Accounts__2__Password: "${MAIL_NOREPLY_PASSWORD:-}"
      Mail__Accounts__3__Address: "privacy@barkfluff.com"
      Mail__Accounts__3__Password: "${MAIL_PRIVACY_PASSWORD:-}"
      Mail__Accounts__4__Address: "security@barkfluff.com"
      Mail__Accounts__4__Password: "${MAIL_SECURITY_PASSWORD:-}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./admindata:/app/db
      - ./docker-compose.yml:/docker-compose.yml:rw
      - ./.env:/.env:ro
    networks:
      - barkfluff-network
    depends_on:
      - settings
      - seq
      - messages

  # === Инфраструктурные сервисы ===

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    ports:
      - "${SEQ_WEBPORT}:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "${SEQ_ADMIN_PASSWORD}"
    volumes:
      - ./data/seq:/data
    networks:
      - barkfluff-network

  #включить для локальной разработки, если нужен S3-совместимый объектный сторедж
  #minio:
  #  image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
  #  container_name: minio
  #  restart: always
  #  ports:
  #    - "${MINIO_PORT}:${MINIO_PORT}"       # S3 API (9000)
  #    - "${MINIO_WEBPORT}:${MINIO_WEBPORT}" # Console (9001)
  #  environment:
  #    MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
  #    MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
  #  volumes:
  #    - ./data/minio:/data
  #  command: server /data --console-address ":${MINIO_WEBPORT}"
  #  networks:
  #    - barkfluff-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - barkfluff-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    networks:
      - barkfluff-network

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    restart: always
    command: --config /etc/livekit/livekit.yaml
    volumes:
      - ./livekit:/etc/livekit:ro
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50200:50000-50200/udp"
    networks:
      - barkfluff-network

  postgres:
    image: postgres:18
    container_name: postgres_barkfluff
    command:
      - "postgres"
      - "-c"
      - "max_connections=150"
      - "-c"
      - "shared_buffers=768MB"
      - "-c"
      - "effective_cache_size=2GB"
      - "-c"
      - "maintenance_work_mem=192MB"
      - "-c"
      - "work_mem=12MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "min_wal_size=512MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_compression=on"
      - "-c"
      - "jit=off"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql
      - ./backups:/backup
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - barkfluff-network

  # включить если нет внешнего nginx, а нужно пробросить порты 80/443 наружу
  #nginx:
  #  image: nginx:alpine
  #  container_name: nginx-proxy
  #  ports:
  #    - "80:80"
  #    - "443:443"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #    - ./sites:/etc/nginx/conf.d:ro
  #    - ./certs:/etc/nginx/certs:ro
  #  restart: always
  #  networks:
  #    - barkfluff-network

networks:
  barkfluff-network:
    external: true
    name: barkfluff-network
