server {
    listen 443 ssl;
    http2 on;
    server_name developers.barkfluff.com;

    ssl_certificate     /etc/nginx/certs/barkfluff.com-crt.pem;
    ssl_certificate_key /etc/nginx/certs/barkfluff.com-key.pem;

    ssl_session_cache   shared:SSL:1m;
    ssl_session_timeout 5m;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    resolver 127.0.0.11 valid=30s ipv6=off;

    root /usr/share/nginx/html;
    index index.html;

    location /grpc/barkfluff.identity.IdentityApi/ {
        rewrite ^/grpc/(.*)$ /$1 break;
        grpc_pass grpcs://identity.barkfluff.com:443;
        grpc_ssl_server_name on;
        grpc_set_header Host identity.barkfluff.com;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto $scheme;
        grpc_read_timeout 300s;
        grpc_send_timeout 300s;
    }

    location /grpc/barkfluff.developers.DevelopersApi/ {
        rewrite ^/grpc/(.*)$ /$1 break;
        grpc_pass grpc://api.barkfluff.com:4425;
        grpc_set_header Host api.barkfluff.com;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto $scheme;
        grpc_read_timeout 300s;
        grpc_send_timeout 300s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}