server {
    listen 443 ssl http2;
    server_name dev.barkfluff.com;

    include /etc/nginx/conf.d/01-ssl-params.conf;
    resolver 127.0.0.11 valid=30s ipv6=off;

    root /usr/share/nginx/developers;
    index index.html;

    location /grpc/barkfluff.identity.IdentityApi/ {
        set $grpc_backend http://IDENTITY_HOST:IDENTITY_PORT;
        proxy_pass $grpc_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location /grpc/barkfluff.developers.DevelopersApi/ {
        set $grpc_backend http://DEVELOPERS_HOST:DEVELOPERS_PORT;
        proxy_pass $grpc_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
