version: '3.8'

x-common-variables: &common-variables
  CONFIGURATION_SERVICE_URL: "${CONFIGURATION_SERVICE_URL}"
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"

services:
  # Основные
  beacon:
    image: docker.barkfluff.com:5000/barkfluff-beacon-dev:latest 
    restart: always
    ports: ["${BEACON_PORT}:${BEACON_PORT}"]
    environment:
      <<: *common-variables
      BEACON_PORT: ${BEACON_PORT}
    networks:
      - barkfluff-network
    depends_on:
      - configuration

  configuration:
    image: docker.barkfluff.com:5000/barkfluff-configuration-dev:latest
    restart: always
    ports: ["${CONFIGURATION_PORT}:${CONFIGURATION_PORT}"]
    env_file:
    - .env
    environment:
      <<: *common-variables
      CONFIGURATION_HOST: ${CONFIGURATION_HOST}
      CONFIGURATION_DATABASE: ${CONFIGURATION_DATABASE}
      CONFIGURATION_USERNAME: ${CONFIGURATION_USERNAME}
      CONFIGURATION_PASSWORD: ${CONFIGURATION_PASSWORD}
      CONFIGURATION_PORT: ${CONFIGURATION_PORT}
    networks:
      - barkfluff-network

  files:
    image: docker.barkfluff.com:5000/barkfluff-files-dev:latest
    restart: always
    ports:
      - "${FILES_PORT}:${FILES_PORT}"
      - "${FILES_HTTP1PORT}:${FILES_HTTP1PORT}"
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - configuration

  identity:
    image: docker.barkfluff.com:5000/barkfluff-identity-dev:latest
    restart: always
    ports: ["${IDENTITY_PORT}:${IDENTITY_PORT}"]
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - configuration

  messages:
    image: docker.barkfluff.com:5000/barkfluff-messages-dev:latest
    restart: always
    ports: ["${MESSAGES_PORT}:${MESSAGES_PORT}"]
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - configuration
  
  notification:
    image: docker.barkfluff.com:5000/barkfluff-notification-dev:latest
    restart: always
    ports: ["${NOTIFICATION_PORT}:${NOTIFICATION_PORT}"]
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - configuration

  users:
    image: docker.barkfluff.com:5000/barkfluff-users-dev:latest
    restart: always
    ports: ["${USERS_PORT}:${USERS_PORT}"]
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - configuration

  fast-auth:
    image: docker.barkfluff.com:5000/barkfluff-fast-auth-dev:latest
    restart: always
    ports: ["${FASTAUTH_PORT}:${FASTAUTH_PORT}"]
    environment:
      <<: *common-variables
      FASTAUTH_PORT: ${FASTAUTH_PORT}
    networks:
      - barkfluff-network
    depends_on:
      - configuration

  updates:
    image: docker.barkfluff.com:5000/barkfluff-updates-dev:latest
    restart: always
    ports: ["${UPDATES_PORT}:${UPDATES_PORT}"]
    environment:
      <<: *common-variables
    networks:
      - barkfluff-network
    depends_on:
      - configuration

    onliner:
      image: docker.barkfluff.com:5000/barkfluff-onliner-dev:latest
      restart: always
      ports: ["${ONLINER_PORT}:${ONLINER_PORT}"]
      environment:
        <<: *common-variables
      network:
        - barkfluff-network
      depends_on:
        - configuration

  # Дополнительные
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    restart: always
    container_name: minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_WEBPORT}:${MINIO_WEBPORT}"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":${MINIO_WEBPORT}"
    networks:
      - barkfluff-network

  rabbitmq:
    image: rabbitmq:latest
    restart: always
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_1PORT}:${RABBITMQ_1PORT}"
      - "${RABBITMQ_2PORT}:${RABBITMQ_2PORT}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - barkfluff-network

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - barkfluff-network

  postgres:
    image: postgres:18
    container_name: postgres_barkfluff
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql
      - backup_volume:/backup
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    networks:
      - barkfluff-network

networks:
  barkfluff-network:
    driver: bridge

volumes:
  pgdata:
  rabbitmq_data:
  redis_data:
  minio_data:
  backup_volume:
