# notification.barkfluff.com - Notification Service (gRPC)
server {
    listen 80;
    server_name notification.barkfluff.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name notification.barkfluff.com;

    include /etc/nginx/conf.d/01-ssl-params.conf;
    resolver 127.0.0.11 valid=30s ipv6=off;

    location / {
        set $grpc_backend grpc://notification:7004;
        grpc_pass $grpc_backend;
        grpc_set_header Host $host;
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        grpc_set_header X-Forwarded-Proto $scheme;
        grpc_read_timeout 300s;
        grpc_send_timeout 300s;
    }
}
