// <auto-generated />
using BarkFluff.Files.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BarkFluff.Files.Persistence.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20260728040000_AddFederatedTempFiles")]
    partial class AddFederatedTempFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The current model is represented by FilesContextModelSnapshot.
            // EF only needs Up/Down at runtime; this marker identifies the migration.
        }
    }
}
