// <auto-generated />
using System;
using System.Collections.Generic;
using BarkFluff.Files.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarkFluff.Files.Persistence.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20260826041416_AddIdempotentUploadOperations")]
    partial class AddIdempotentUploadOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarkFluff.Files.Domain.BadgeImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Etag")
                        .HasColumnType("text");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BadgeImages");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.FileHash", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("FileId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("FileHashes");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.Sticker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviewFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StickerPackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StickerPackId");

                    b.ToTable("Stickers");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.StickerPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoverStickerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("StickerPacks");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.TempFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AttachmentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("OriginServer")
                        .HasColumnType("text");

                    b.Property<Guid>("OriginalFileId")
                        .HasColumnType("uuid");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OriginalFileId");

                    b.ToTable("TempFiles");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.UploadFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Etag")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Filename")
                        .HasColumnType("text");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviewId")
                        .HasColumnType("uuid");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<long>>("Uploaders")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("Id");

                    b.HasIndex("PreviewId")
                        .HasFilter("\"PreviewId\" IS NOT NULL");

                    b.HasIndex("Uploaders");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Uploaders"), "gin");

                    b.ToTable("UploadedFiles");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.UploadOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientOperationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReservedFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResultFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReservedFileId")
                        .IsUnique();

                    b.HasIndex("State", "LeaseExpiresAt");

                    b.HasIndex("UserId", "ClientOperationId")
                        .IsUnique()
                        .HasFilter("\"ClientOperationId\" IS NOT NULL");

                    b.ToTable("UploadOperations");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.Sticker", b =>
                {
                    b.HasOne("BarkFluff.Files.Domain.StickerPack", "StickerPack")
                        .WithMany("Stickers")
                        .HasForeignKey("StickerPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StickerPack");
                });

            modelBuilder.Entity("BarkFluff.Files.Domain.StickerPack", b =>
                {
                    b.Navigation("Stickers");
                });
#pragma warning restore 612, 618
        }
    }
}
