// <auto-generated />
using BarkFluff.Federation.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarkFluff.Federation.Persistence.Migrations
{
    [DbContext(typeof(FederationContext))]
    [Migration("20260718040000_AddKnownServers")]
    partial class AddKnownServers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.FederationSigningKey", b =>
                {
                    b.Property<string>("KeyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PrivateKeySeed")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KeyId");

                    b.ToTable("SigningKeys");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServer", b =>
                {
                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("FederationEndpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastKeyRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("TlsSpkiSha256")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ServerName");

                    b.ToTable("KnownServers");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServerKey", b =>
                {
                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("KeyId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServerName", "KeyId");

                    b.ToTable("KnownServerKeys");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServerKey", b =>
                {
                    b.HasOne("BarkFluff.Federation.Domain.Entities.KnownServer", "Server")
                        .WithMany("Keys")
                        .HasForeignKey("ServerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServer", b =>
                {
                    b.Navigation("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
