// <auto-generated />
using BarkFluff.Federation.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarkFluff.Federation.Persistence.Migrations
{
    [DbContext(typeof(FederationContext))]
    partial class FederationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.FederationOutbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PayloadBytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Destination", "ChatId", "Id")
                        .HasDatabaseName("IX_Outbox_Destination_ChatId_Id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("IX_Outbox_Status_NextAttemptAt");

                    b.ToTable("FederationOutbox", (string)null);
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.FederationSigningKey", b =>
                {
                    b.Property<string>("KeyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PrivateKeySeed")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KeyId");

                    b.ToTable("SigningKeys");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServer", b =>
                {
                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("FederationEndpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastKeyRefreshAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("TlsSpkiSha256")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ServerName");

                    b.ToTable("KnownServers");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServerKey", b =>
                {
                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("KeyId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServerName", "KeyId");

                    b.ToTable("KnownServerKeys");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginServer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServerKey", b =>
                {
                    b.HasOne("BarkFluff.Federation.Domain.Entities.KnownServer", "Server")
                        .WithMany("Keys")
                        .HasForeignKey("ServerName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("BarkFluff.Federation.Domain.Entities.KnownServer", b =>
                {
                    b.Navigation("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
