// <auto-generated />
using BarkFluff.Navigator.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarkFluff.Navigator.Persistence.Migrations
{
    [DbContext(typeof(NavigatorContext))]
    partial class NavigatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarkFluff.Navigator.Domain.ServerInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BeaconHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BeaconPort")
                        .HasColumnType("integer");

                    b.Property<string>("ColorHardHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorLiteHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorMainHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FederationEndpoint")
                        .HasColumnType("text");

                    b.Property<int[]>("FederationProtocolVersions")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServerName")
                        .HasColumnType("text");

                    b.Property<string>("ServerPublicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SigningKeys")
                        .HasColumnType("jsonb");

                    b.Property<string[]>("TlsSpkiSha256")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ServerName")
                        .IsUnique()
                        .HasFilter("\"ServerName\" IS NOT NULL");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
