upstream barkfluff_clientstorage {
    server clientstorage:7050;
}

server {
    listen 443 ssl;
    http2 on;
    server_name storage.barkfluff.com;
    include /etc/nginx/conf.d/01-ssl-params.conf;
    resolver 127.0.0.11 valid=30s ipv6=off;
    client_max_body_size 512m;
    client_body_timeout 1800s;
    location / {
        proxy_pass http://barkfluff_clientstorage;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_http_version 1.1;
        proxy_request_buffering off;
        proxy_read_timeout 1800s;
        proxy_send_timeout 1800s;
        proxy_connect_timeout 60s;
    }
}
