syntax = "proto3";

option csharp_namespace = "BarkFluff.Proto.Updates";

import "google/protobuf/timestamp.proto";
import "shared.proto";

package barkfluff.updates;

service UpdatesApi {

  // Подписаться на новые сообщения
  rpc SubscribeNewMessages(SubscribeNewMessagesRequest) returns (stream NewMessageEvent);

  rpc SubscribeMessagesRead(SubscribeMessagesReadRequest) returns(stream MessageReadEvent);

  // Подписаться на отредактированные сообщения
  rpc SubscribeMessagesEdited(SubscribeMessagesEditedRequest) returns (stream MessageEditedEvent);

  // Подписаться на удалённые сообщения
  rpc SubscribeMessagesDeleted(SubscribeMessagesDeletedRequest) returns (stream MessageDeletedEvent);
}

message SubscribeNewMessagesRequest {
  
}

message SubscribeMessagesReadRequest {
  
}

message NewMessageEvent {
  barkfluff.shared.Message message = 1; //Отправленное сообщение
  
  string chat_id = 2; // Идентификатор чата на который пришло сообщение
}

message MessageReadEvent {
  string chat_id = 1; // Идентификатор чата
  int64 message_id = 2; // Идентификатор прочитанного сообщения
  repeated int64 new_read_by = 3; // Новый read_by сообщения (НЕ ТОЛЬКО НОВЫЕ, А ПОЛНОСТЬЮ ВСЕ, КТО ПРОЧИТАЛ)
}

message SubscribeMessagesEditedRequest {

}

message SubscribeMessagesDeletedRequest {

}

message MessageEditedEvent {
  string chat_id = 1; // Идентификатор чата
  barkfluff.shared.Message message = 2; // Обновлённое сообщение
}

message MessageDeletedEvent {
  string chat_id = 1; // Идентификатор чата
  int64 message_id = 2; // Идентификатор удалённого сообщения
}

