// <auto-generated />
using BarkFluff.Users.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BarkFluff.Users.Persistence.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20260721040000_AddDenyFederatedDm")]
    partial class AddDenyFederatedDm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The current model is represented by UsersContextModelSnapshot.
            // EF only needs Up/Down at runtime; this marker identifies the migration.
        }
    }
}
