<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.30.2" />
      <PackageReference Include="Grpc.AspNetCore.Server" Version="2.70.0" />
      <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.70.0" />
      <PackageReference Include="Grpc.Net.Client" Version="2.70.0" />
      <PackageReference Include="Grpc.Tools" Version="2.71.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.8.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\BarkFluff.Shared.Exceptions\BarkFluff.Shared.Exceptions.csproj" />
      <ProjectReference Include="..\..\Shared\BarkFluff.Shared.Auth\BarkFluff.Shared.Auth.csproj" />
      <ProjectReference Include="..\..\Shared\BarkFluff.Shared.Identity\BarkFluff.Shared.Identity.csproj" />
    </ItemGroup>


    <ItemGroup>
        <Protobuf Include="..\..\Shared\BarkFluff.Proto\configuration_api.proto" GrpcServices="Client" />
    </ItemGroup>

</Project>
