// <auto-generated />
using System;
using BarkFluff.Calls.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarkFluff.Calls.Persistence.Migrations
{
    [DbContext(typeof(CallsContext))]
    [Migration("20260621223642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarkFluff.Calls.Domain.CallSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CalleeUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("CallerUserId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<int>("EndReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("EndedByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Media")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalleeUserId");

                    b.HasIndex("ChatId");

                    b.HasIndex("Status");

                    b.ToTable("CallSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
