services:
  webserver-dev:
    container_name: webserver
    image: docker.barkfluff.com/barkfluff-webserver-dev:latest
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:${WEBSERVER_PORT}"
      WEBSERVER_PORT: ${WEBSERVER_PORT}
      Telegram__BotToken: ${TELEGRAM_BOT_TOKEN}
      UsersService__Host: ${USERS_SERVICE_HOST}
      UsersService__Token: ${USERS_SERVICE_TOKEN}
    networks:
      - barkfluff-network

networks:
  barkfluff-network:
    external: true
    name: barkfluff-network
