<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\BarkFluff.Shared.Queue\BarkFluff.Shared.Queue.csproj" />
      <ProjectReference Include="..\BarkFluff.GrpcServer\BarkFluff.GrpcServer.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Templates\confirmation_auth.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\confirmation_otp_email.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\confirmation_account.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\failed_login.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\password_changed.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\reset_password.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\successful_login.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\successful_registration.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Templates\two_factor_method_changed.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
