// <auto-generated />
using BarkFluff.Messages.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BarkFluff.Messages.Persistence.Migrations
{
    [DbContext(typeof(MessagesContext))]
    [Migration("20260710120000_AddPrivateChatListing")]
    partial class AddPrivateChatListing
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // The current model is represented by MessagesContextModelSnapshot.
            // EF only needs Up/Down at runtime; this marker identifies the migration.
        }
    }
}
