// <auto-generated />
using System;
using System.Collections.Generic;
using BarkFluff.Messages.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarkFluff.Messages.Migrations
{
    [DbContext(typeof(MessagesContext))]
    [Migration("20260502205903_AddForwardedMessageAttachment")]
    partial class AddForwardedMessageAttachment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarkFluff.Messages.Domain.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsGroupChat")
                        .HasColumnType("boolean");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("BarkFluff.Messages.Domain.ChatMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "UserId");

                    b.ToTable("ChatMembers");
                });

            modelBuilder.Entity("BarkFluff.Messages.Domain.GroupChatInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<long>>("UsersCanKick")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.HasKey("Id");

                    b.ToTable("GroupChatInfos");
                });

            modelBuilder.Entity("BarkFluff.Messages.Domain.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<long>>("ReadBy")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BarkFluff.Messages.Domain.ChatMember", b =>
                {
                    b.HasOne("BarkFluff.Messages.Domain.Chat", "Chat")
                        .WithMany("Members")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("BarkFluff.Messages.Domain.Message", b =>
                {
                    b.OwnsOne("BarkFluff.Messages.Domain.MessageContent", "Content", b1 =>
                        {
                            b1.Property<long>("MessageId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Text")
                                .HasColumnType("text");

                            b1.HasKey("MessageId");

                            b1.ToTable("Messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");

                            b1.OwnsMany("BarkFluff.Messages.Domain.MessageAttachment", "Attachments", b2 =>
                                {
                                    b2.Property<long>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("bigint");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<long>("Id"));

                                    b2.Property<string>("FileId")
                                        .HasColumnType("text");

                                    b2.Property<long>("FileSize")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ForwardedAuthorName")
                                        .HasColumnType("text");

                                    b2.Property<long?>("ForwardedOriginalMessageId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("ForwardedText")
                                        .HasColumnType("text");

                                    b2.Property<long>("MessageId")
                                        .HasColumnType("bigint");

                                    b2.Property<string>("PreviewUrl")
                                        .HasColumnType("text");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("Id");

                                    b2.HasIndex("MessageId");

                                    b2.ToTable("MessageAttachments");

                                    b2.WithOwner()
                                        .HasForeignKey("MessageId");

                                    b2.OwnsMany("BarkFluff.Messages.Domain.ForwardedMessageAttachment", "ForwardedAttachments", b3 =>
                                        {
                                            b3.Property<long>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("bigint");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<long>("Id"));

                                            b3.Property<string>("FileId")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<long>("FileSize")
                                                .HasColumnType("bigint");

                                            b3.Property<long>("MessageAttachmentId")
                                                .HasColumnType("bigint");

                                            b3.Property<string>("PreviewUrl")
                                                .HasColumnType("text");

                                            b3.Property<int>("Type")
                                                .HasColumnType("integer");

                                            b3.HasKey("Id");

                                            b3.HasIndex("MessageAttachmentId");

                                            b3.ToTable("ForwardedMessageAttachment");

                                            b3.WithOwner()
                                                .HasForeignKey("MessageAttachmentId");
                                        });

                                    b2.Navigation("ForwardedAttachments");
                                });

                            b1.Navigation("Attachments");
                        });

                    b.Navigation("Content");
                });

            modelBuilder.Entity("BarkFluff.Messages.Domain.Chat", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
