// <auto-generated />
using BarkFluff.Messages.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace BarkFluff.Messages.Persistence.Migrations;

[DbContext(typeof(MessagesContext))]
[Migration("20260801000000_AddChatDrafts")]
partial class AddChatDrafts
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // The current model is represented by MessagesContextModelSnapshot.
    }
}
