x-common-variables: &common-variables
  CONFIGURATION_SERVICE_URL: "http://192.168.1.177:7003"
  ASPNETCORE_ENVIRONMENT: Production

services:
  navigator:
    image: docker.barkfluff.com:5000/barkfluff-navigator:latest
    restart: always
    ports: [ "${NAVIGATOR_PORT}:${NAVIGATOR_PORT}" ]
    environment:
      <<: *common-variables
      NAVIGATOR_PORT: ${NAVIGATOR_PORT}
    networks:
      - barkfluff-network

networks:
  barkfluff-network:
    driver: bridge
