syntax = "proto3";

option csharp_namespace = "BarkFluff.Proto.Files";

import "google/protobuf/timestamp.proto";

package barkfluff.files;

service FilesApi {
  rpc GetUploadUrl(GetUploadUrlRequest) returns(GetUploadUrlResponse); // Получить ссылку для загрузки файла
  
  rpc GetTempDownloadUrl(GetTempDownloadUrlRequest) returns(GetTempDownloadUrlResponse); // Получить ссылку для скачивания файла
}

service FilesServerApi {
  rpc GetFileData(GetFileDataRequest) returns(GetFileDataResponse); // Получить информацию о загруженном файле
  
  rpc GetFilesData(GetFilesDataRequest) returns(GetFilesDataResponse); // Получить информацию о загруженных файлах
}

message GetTempDownloadUrlRequest {
  repeated string file_ids = 1; // Идентификаторы файлов
}

message GetTempDownloadUrlResponse {
  
  message DownloadFileData {
    string file_id = 1; // идентификатор файла
    string url = 2; // ссылка на загрузку
  }
  
  repeated DownloadFileData file_urls = 1; // ссылки на файлы
  
}

message GetFilesDataRequest {
  repeated string file_ids = 1; // Идентификаторы файлов
}

message GetFilesDataResponse {
  repeated UploadFileInfo files_infos = 1; // Информация о файлах
}

message GetFileDataRequest {
  string file_id = 1;
}

message GetFileDataResponse {
    UploadFileInfo file_info = 1;
}

message UploadFileInfo {
  string id = 1; // Идентификатор файла
  int64 uploader = 2; // Индетификатор загрузившего пользователя
  google.protobuf.Timestamp created_at = 3; // Время создания
  google.protobuf.Timestamp uploaded_at = 4; // время загрузки
  string etag = 5; // Etag S3
  UploadFileType type = 6; // Тип загруженного файла
  string file_name = 7; // Имя файла
  string file_url = 8; // Ссылка на загрузку файла
}

message GetUploadUrlRequest {
  UploadFileType file_type = 1; // Тип загружаемого файла
}

message GetUploadUrlResponse {
  string url = 1; // адрес для загрузки файла
  string file_id = 2; // идентификатор файла
}

enum UploadFileType {
  UPLOAD_FILE_TYPE_UNKNOWN = 0; 
  
  USER_AVATAR = 1; // Аватарка пользователя
  
  MESSAGE_ATTACHMENT_IMAGE = 2; // Вложение сообщения - изображение
  
  MESSAGE_ATTACHMENT_VIDEO = 3; // Вложение сообщения - видео
  
  MESSAGE_ATTACHMENT_GIF = 4; // Вложение сообщения - гифка 
  
  MESSAGE_ATTACHMENT_DOCUMENT = 5; // Вложение сообщения - документ
}