syntax = "proto3";

option csharp_namespace = "BarkFluff.Proto.Navigator";

import "google/protobuf/timestamp.proto";

package barkfluff.navigator;


service NavigatorApi {
  rpc ListServers(ListServersRequest) returns (ListServersResponse);
  rpc RegisterServer(RegisterServerRequest) returns (RegisterServerResponse);
}

message ListServersRequest {
  
}

message ListServersResponse {
  repeated ServerInfo servers = 1; // Сервера
}

message ServerInfo {
  string name = 1; // Имя сервера
  string description = 2; // Описание
  int64 accounts_count = 3; // Количество пользователей
  ServiceEndpoint beacon_uri = 4; // Адрес маяка
  string server_public_name = 5; // Публичное имя сервера
}

message ServiceEndpoint {
  string host = 1; // Хост
  int32 port = 2; // Порт
}

message RegisterServerRequest {
  ServerInfo server = 1; // Данные о сервере
}

message RegisterServerResponse {
  // Можно добавить поля при необходимости, пока пусто
}
