syntax = "proto3";

option csharp_namespace = "BarkFluff.Proto.Navigator";

import "google/protobuf/timestamp.proto";

package barkfluff.navigator;


service NavigatorApi {
  rpc ListServers(ListServersRequest) returns (ListServersResponse);
}

message ListServersRequest {
  
}

message ListServersResponse {
  repeated ServerInfo servers = 1; // Сервера
}

message ServerInfo {
  string name = 1; // Имя сервера
  string description = 2; // Описание
  int64 accounts_count = 3; // Количество пользователей
  ServiceEndpoint beacon_uri = 4; // Адрес маяка
}

message ServiceEndpoint {
  string host = 1; // Хост
  int32 port = 2; // Порт
}
