syntax = "proto3";

option csharp_namespace = "BarkFluff.Proto.Shared";

import "google/protobuf/timestamp.proto";

package barkfluff.shared;

message PageRequest {
  
  int32 offset = 1; // Количество элементов для пропуска
  
  int32 size = 2; // Размер элементов на странице
  
}

message Message {

  int64 id = 1; // Идетификатор сообщения

  int64 sender_id = 2; // Идентификатор отправителя

  repeated int64 read_by = 3; // Идентификатор пользователей, которые прочитали сообщение

  google.protobuf.Timestamp sent_at = 4; // Дата отправки сообщения

  MessageContent content = 5; // Содержимое сообщения

  MessageContentType type = 6; // Тип сообщения

}

message MessageContent {

  string text = 1; // Текст сообщения

  repeated MessageAttachment attachments = 2; // Вложения
}

message MessageAttachment {

  int64 id = 1; // Идентификатор вложения

  MessageAttachmentType type = 2; // Тип вложения

  string file_id = 3; // Индетификатор файла
}

enum MessageAttachmentType {

  MESSAGE_ATTACHMENT_TYPE_UNKNOWN = 0; // Неизвестно 

  IMAGE = 1; // Изображение

  VIDEO = 2; // Видео

  GIF = 3; // Гифка

  DOCUMENT = 4; // Документ
}

enum MessageContentType {

  MESSAGE_CONTENT_TYPE_UNKNOWN = 0; // Неизвестно

  GENERIC = 1; // Обычное содержимое

  SYSTEM = 2; // Системное содержимое
}

