syntax = "proto3";

option csharp_namespace = "BarkFluff.Proto.Updates";

import "google/protobuf/timestamp.proto";
import "shared.proto";

package barkfluff.updates;

service UpdatesApi {

  // Подписаться на новые сообщения
  rpc SubscribeNewMessages(SubscribeNewMessagesRequest) returns (stream NewMessageEvent);

  rpc SubscribeMessagesRead(SubscribeMessagesReadRequest) returns(stream MessageReadEvent);

  // Подписаться на события редактирования сообщений
  rpc SubscribeMessagesEdited(SubscribeMessagesEditedRequest) returns (stream MessageEditedEvent);

  // Подписаться на события удаления сообщений
  rpc SubscribeMessagesDeleted(SubscribeMessagesDeletedRequest) returns (stream MessageDeletedEvent);

  // Подписаться на события закрепления сообщений
  rpc SubscribeMessagesPinned(SubscribeMessagesPinnedRequest) returns (stream MessagePinnedEvent);

  // Подписаться на события открепления сообщений
  rpc SubscribeMessagesUnpinned(SubscribeMessagesUnpinnedRequest) returns (stream MessageUnpinnedEvent);

  // Подписаться на события открепления всех сообщений в чате
  rpc SubscribeAllMessagesUnpinned(SubscribeAllMessagesUnpinnedRequest) returns (stream AllMessagesUnpinnedEvent);
}

message SubscribeNewMessagesRequest {

}

message SubscribeMessagesReadRequest {

}

message SubscribeMessagesEditedRequest { }

message SubscribeMessagesDeletedRequest { }

message SubscribeMessagesPinnedRequest { }

message SubscribeMessagesUnpinnedRequest { }

message SubscribeAllMessagesUnpinnedRequest { }

message NewMessageEvent {
  barkfluff.shared.Message message = 1; //Отправленное сообщение
  
  string chat_id = 2; // Идентификатор чата на который пришло сообщение
}

message MessageReadEvent {
  string chat_id = 1; // Идентификатор чата
  int64 message_id = 2; // Идентификатор прочитанного сообщения
  repeated int64 new_read_by = 3; // Новый read_by сообщения (НЕ ТОЛЬКО НОВЫЕ, А ПОЛНОСТЬЮ ВСЕ, КТО ПРОЧИТАЛ)
}

message MessageEditedEvent {
  string chat_id = 1; // Идентификатор чата
  barkfluff.shared.Message message = 2; // Обновленное сообщение
}

message MessageDeletedEvent {
  string chat_id = 1; // Идентификатор чата
  int64 message_id = 2; // Идентификатор удаленного сообщения
}

message MessagePinnedEvent {
  string chat_id = 1; // Идентификатор чата
  int64 message_id = 2; // Идентификатор закреплённого сообщения
  int64 pinner_user_id = 3; // Кто закрепил
  google.protobuf.Timestamp pinned_at = 4; // Дата закрепления (UTC)
}

message MessageUnpinnedEvent {
  string chat_id = 1; // Идентификатор чата
  int64 message_id = 2; // Идентификатор откреплённого сообщения
}

message AllMessagesUnpinnedEvent {
  string chat_id = 1; // Идентификатор чата, где откреплены все сообщения
}

