syntax = "proto3";

option csharp_namespace = "BarkFluff.Proto.Users";

import "google/protobuf/timestamp.proto";

package barkfluff.users;

service UsersApi {
  rpc SetPassword(SetPasswordRequest) returns(SetPasswordResponse);
  
  rpc GetUser(GetUserRequest) returns(GetUserResponse);
}

service UsersServerApi {
  
  rpc FindByLogin(FindByLoginRequest) returns(FindByLoginResponse);

  rpc CheckExistUsername(CheckExistUsernameRequest) returns(CheckExistResponse);
  
  rpc CheckExistEmail(CheckExistEmailRequest) returns(CheckExistResponse);
  
  rpc AddDraftUser(AddDraftUserRequest) returns(AddDraftUserResponse);
  
  rpc ConfirmUser(ConfirmUserRequest) returns(ConfirmUserResponse);
}

message GetUserRequest {
  int64 user_id = 1;
}

message GetUserResponse {
  User user = 1;
}

message ConfirmUserRequest {
  int64 user_id = 1;
}

message ConfirmUserResponse {
  
}


message SetPasswordRequest {
  string password = 1;
}

message SetPasswordResponse { }

message AddDraftUserRequest {
  string first_name = 1;
  string last_name = 2;
  string username = 3;
  string email = 4;
}

message AddDraftUserResponse {
  int64 user_id = 1;
}

message CheckExistEmailRequest {
  string email = 1;
}

message CheckExistUsernameRequest {
  string username = 1;
}

message CheckExistResponse {
  bool exist = 1;
}


message FindByLoginRequest {
  oneof login {
    string username = 1;
    string email = 2;
  }
}

message FindByLoginResponse {
  User user = 1;
}

message User{
  int64 id = 1;
  string first_name = 2;
  string last_name = 3;
  string username = 4;
  google.protobuf.Timestamp registration_date = 5;
}

