services:
  clientstorage-nightly:
    container_name: clientstorage
    image: docker.barkfluff.com/barkfluff-client-storage-nightly:latest
    restart: always

    volumes:
      - clientstorage-data:/app/data
      - clientstorage-cache:/app/cache

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:${CLIENTSTORAGE_PORT}"

      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_SERVICE_URL: ${S3_SERVICE_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      REGISTRY_STORAGE_S3_CHUNKSIZE: ${REGISTRY_STORAGE_S3_CHUNKSIZE}

      UPLOAD_TOKEN: ${UPLOAD_TOKEN}
      CLIENTSTORAGE_PORT: ${CLIENTSTORAGE_PORT}

    networks:
      barkfluff-network:
        aliases:
          - barkfluff_clientstorage

volumes:
  clientstorage-data:
  clientstorage-cache:

networks:
  barkfluff-network:
    external: true
    name: barkfluff-network
