using BarkFluff.Onliner.Domain.Entities;
using BarkFluff.Onliner.Domain.Enums;
using BarkFluff.Onliner.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;

namespace BarkFluff.Onliner.Tests.Persistence;

public class OnlineStatusContextTests
{
    private OnlineStatusContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<OnlineStatusContext>()
            .UseInMemoryDatabase(Guid.NewGuid().ToString())
            .Options;
        return new OnlineStatusContext(options);
    }

    [Fact]
    public async Task SaveChangesAsync_PersistsUserOnlineStatus()
    {
        using var ctx = CreateContext();
        var status = new UserOnlineStatus
        {
            UserId = 1,
            Status = StatusTypeId.Online,
            LastSeen = DateTime.UtcNow
        };

        ctx.UsersOnlineStatuses.Add(status);
        await ctx.SaveChangesAsync();

        var saved = await ctx.UsersOnlineStatuses.FindAsync(1L);
        saved.Should().NotBeNull();
        saved!.UserId.Should().Be(1);
        saved.Status.Should().Be(StatusTypeId.Online);
    }

    [Fact]
    public async Task FindAsync_NonExistent_ReturnsNull()
    {
        using var ctx = CreateContext();

        var result = await ctx.UsersOnlineStatuses.FindAsync(999L);

        result.Should().BeNull();
    }

    [Fact]
    public async Task SaveChangesAsync_UpdatesExistingRecord()
    {
        using var ctx = CreateContext();
        var status = new UserOnlineStatus
        {
            UserId = 1,
            Status = StatusTypeId.Online,
            LastSeen = DateTime.UtcNow
        };
        ctx.UsersOnlineStatuses.Add(status);
        await ctx.SaveChangesAsync();

        var existing = await ctx.UsersOnlineStatuses.FindAsync(1L);
        ctx.Entry(existing!).CurrentValues.SetValues(new UserOnlineStatus
        {
            UserId = 1,
            Status = StatusTypeId.Offline,
            LastSeen = DateTime.UtcNow
        });
        await ctx.SaveChangesAsync();

        var updated = await ctx.UsersOnlineStatuses.FindAsync(1L);
        updated!.Status.Should().Be(StatusTypeId.Offline);
    }

    [Fact]
    public async Task SaveChangesAsync_MultipleUsers()
    {
        using var ctx = CreateContext();
        ctx.UsersOnlineStatuses.Add(new UserOnlineStatus
        {
            UserId = 1,
            Status = StatusTypeId.Online,
            LastSeen = DateTime.UtcNow
        });
        ctx.UsersOnlineStatuses.Add(new UserOnlineStatus
        {
            UserId = 2,
            Status = StatusTypeId.Offline,
            LastSeen = DateTime.UtcNow
        });
        await ctx.SaveChangesAsync();

        var count = await ctx.UsersOnlineStatuses.CountAsync();
        count.Should().Be(2);
    }

    [Fact]
    public async Task UserId_IsPrimaryKey()
    {
        using var ctx = CreateContext();
        var entity = ctx.Model.FindEntityType(typeof(UserOnlineStatus))!;
        var pk = entity.FindPrimaryKey()!;

        pk.Properties.Should().ContainSingle(p => p.Name == "UserId");
    }

    [Fact]
    public async Task UserId_IsNotAutoGenerated()
    {
        using var ctx = CreateContext();
        var entity = ctx.Model.FindEntityType(typeof(UserOnlineStatus))!;
        var userIdProp = entity.FindProperty("UserId")!;

        userIdProp.ValueGenerated.Should().Be(Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never);
    }
}
