name: Deploy Microservices
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'Backend/BarkFluff.**/**'
      - '.github/workflows/deploy-microservices.yml'

jobs:
  detect-changes:
    runs-on: ["self-hosted", "windows"]
    outputs:
      changes: ${{ steps.filter.outputs }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            beacon:
              - 'Backend/BarkFluff.Beacon/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            configuration:
              - 'Backend/BarkFluff.Configuration/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            files:
              - 'Backend/BarkFluff.Files/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            identity:
              - 'Backend/BarkFluff.Identity/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            messages:
              - 'Backend/BarkFluff.Messages/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            notification:
              - 'Backend/BarkFluff.Notification/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            users:
              - 'Backend/BarkFluff.Users/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            fast-auth:
              - 'Backend/BarkFluff.FastAuth/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            navigator:
              - 'Backend/BarkFluff.Navigator/**'
              - 'Backend/BarkFluff.GrpcServer/**'
            updates:
              - 'Backend/BarkFluff.Updates/**'
              - 'Backend/BarkFluff.GrpcServer/**'

  build:
    needs: detect-changes
    runs-on: ["self-hosted", "windows"]
    strategy:
      matrix:
        include:
          - name: beacon
            path: ./Backend/BarkFluff.Beacon/Dockerfile
            image: barkfluff-beacon
          - name: configuration
            path: ./Backend/BarkFluff.Configuration/Dockerfile
            image: barkfluff-configuration
          - name: files
            path: ./Backend/BarkFluff.Files/Dockerfile
            image: barkfluff-files
          - name: identity
            path: ./Backend/BarkFluff.Identity/Dockerfile
            image: barkfluff-identity
          - name: messages
            path: ./Backend/BarkFluff.Messages/Dockerfile
            image: barkfluff-messages
          - name: notification
            path: ./Backend/BarkFluff.Notification/Dockerfile
            image: barkfluff-notification
          - name: users
            path: ./Backend/BarkFluff.Users/Dockerfile
            image: barkfluff-users
          - name: fast-auth
            path: ./Backend/BarkFluff.FastAuth/Dockerfile
            image: barkfluff-fast-auth
          - name: navigator
            path: ./Backend/BarkFluff.Navigator/Dockerfile
            image: barkfluff-navigator
          - name: updates
            path: ./Backend/BarkFluff.Updates/Dockerfile
            image: barkfluff-updates
    if: ${{ fromJSON(needs.detect-changes.outputs.changes)[matrix.name] == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Private Registry
        uses: docker/login-action@v2
        with:
          registry: docker.barkfluff.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Define tags
        shell: bash
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then
            echo "LATEST_TAG=docker.barkfluff.com/${{ matrix.image }}:latest-dev" >> $GITHUB_ENV
            echo "SHA_TAG=docker.barkfluff.com/${{ matrix.image }}:${{ github.sha }}-dev" >> $GITHUB_ENV
          else
            echo "LATEST_TAG=docker.barkfluff.com/${{ matrix.image }}:latest" >> $GITHUB_ENV
            echo "SHA_TAG=docker.barkfluff.com/${{ matrix.image }}:${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Build and Push ${{ matrix.image }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.path }}
          push: true
          tags: ${{ env.LATEST_TAG }},${{ env.SHA_TAG }}
